/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void backButton_click1(GButton source, GEvent event) { //_CODE_:backButton1:397388:
  //if (currentUser == null) {
  //    introComplete = false; // Navigate back to the intro screen
  //  } else {
  //    currentQuestion--;
  //    if (currentQuestion < 0) {
  //      currentQuestion = questions.length +2;
  //    }
  //  }

  //displayQuestions();
  println("button1 - GButton >> GEvent." + event + " @ " + millis());

} //_CODE_:backButton1:397388:

public void button2_click1(GButton source, GEvent event) { //_CODE_:backButton2:968307:
  //showRecommendations = false;
  //showUserRecommendations = false;
  //displayLogin();
  println("backButton2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:backButton2:968307:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  backButton1 = new GButton(this, 40, 651, 94, 33);
  backButton1.setText("Switch User / Logout");
  backButton1.addEventHandler(this, "backButton_click1");
  backButton2 = new GButton(this, 157, 651, 80, 30);
  backButton2.setText("Recomend Destination");
  backButton2.addEventHandler(this, "button2_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton backButton1; 
GButton backButton2; 
